# এক প্যাকেজে সবকিছু, জুপিটার এবং কোলাব নোটবুক

মেশিন লার্নিং এর বেশকিছু টুলসগুলো নিয়ে আলাপ করার আগে একটা বিষয়ে আশ্বস্ত করতে চাই সবাইকে। মেশিন লার্নিং এর পাশাপাশি ডাটা সাইন্সের বিভিন্ন টুলসগুলোর পপুলারিটি বাড়তে থাকায় কেউ কেউ ওই দরকারি সব ওপেনসোর্স প্যাকেজগুলোকে এক জায়গায় নিয়ে এসেছেন। মানে, বুঝতেই পারছেন উইন্ডোজে এক ক্লিকে ইনস্টল! আমি লিনাক্স ব্যবহার করি বলে বলতে পারি - সেখানেও জিনিসটা চলে এসেছে পানির পর্যায়ে। 
পাইথনে মেশিন লার্নিং নিয়ে কাজ করলে সবাই শুরু করে 'সাইকিট-লার্ন' দিয়ে। আসলেই তাই। অসাধারণ মেশিন লার্নিং লাইব্রেরি। ডকুমেন্টেশনও অন্য লেভেলের। এই জিনিসটা আবার আরো দুটো পাইথন প্যাকেজের ওপর ভর করে চলে। তার একটা হচ্ছে 'নামপাই', আরেকটা 'সাইপাই'। মানুষ আবার ছবি ছাড়া কিছু বোঝে না। সেই 'স্টানিং' ভিজ্যুয়ালাইজেশনের জন্য আমরা ব্যবহার করবো 'ম্যাটপ্লটলিব'। ডাটাকে খুঁচিয়ে দেখতে 'পান্ডাজ' এর জুড়ি নেই। ডাটা অ্যানালাইসিস করতে লাগবে একে। তো, আমাদের ইন্টারফেস কি হবে? 'আই-পাইথন' ছাড়া আর কে? 'ইন্টার-অ্যাক্টিভ' মানে দেখে দেখে কাজ করার জন্য 'জুপিটার নোটবুক' ছাড়া আমরা অচল। পাইথন তো আছেই। তো, এই আটটা টুল সহ আরো হাজারো ডাটা সাইন্স টুল পাবো কোথায়?--- অ্যানাকন্ডা! মানে পাইথনের বড় ভাই। এই ডিস্ট্রিবিউশনটা তৈরি করা হয়েছে বিশাল স্কেলের ডাটা প্রসেসিং, প্রেডিক্টিভ অ্যানালাইসিস আর দরকারি সাইন্টিফিক কম্পিউটিং এর জন্য। দুটো ডিস্ট্রবিউশনে ইন্টেলের কমার্শিয়াল 'এমকেএল' লাইব্রেরি আছে - ফ্রী! 'সাইকিট-লার্ন' এর মেশিন লার্নিং অ্যালগরিদমগুলোর গতি এনে দেয় এই জিনিস। <br>
এখন চলুন ইনস্টল করে নেই অ্যানাকন্ডা ডাটা সাইন্স ডিস্ট্রিবিউশন প্যাকেজ। পাওয়া যাবে নিচের লিংকে। <br>
https://www.anaconda.com/download/ <br>
১. উইন্ডোজ ব্যবহারকারীদের জন্য ইনস্টলারটা খুবই সহজ। ডাউনলোড করে ডাবল ক্লিক করে ইনস্টলারটা চালু করুন। <br>
২. লাইসেন্স টার্ম মেনে নিন। নেক্সট চাপুন। <br>
৩. ইনস্টলেশন ডিরেক্টরি বেছে নিন। সতর্কতাবাণী হচ্ছে, অনুগ্রহ করে কোন স্পেস বা 'ইউনিকোড ক্যারেক্টার' রাখবেন না। না মানে না। বাংলা ইউনিকোড ক্যারেক্টার। <br>
৪. আমাদের এই ইনস্টলেশনে 'অ্যাডমিনিস্ট্রেটিভ প্রিভিলেজ' লাগে না।<br>
৫.  অ্যানাকন্ডাকে কোন পাথ এনভায়রনমেন্টে যোগ করার দরকার নেই। যোগ করলেই সমস্যা বাড়ে। অ্যানাকন্ডা আপডেট বা অন্যান্য কিছু করতে চাইলে স্টার্ট মেন্যু থেকে অ্যানাকন্ডা নেভিগেটর বা অ্যানাকন্ডা প্রম্প্ট দিয়ে কাজ করতে পারেন। <br>
৬. "রেজিস্টার অ্যানাকন্ডা অ্যাজ মাই ডিফল্ট পাইথন ৩.৬" চেকবক্সটি দয়া করে আনচেক করবেন না। ডিফল্ট চেক মেনে নিন। <br>
৭. 'মাইক্রোসফট ভিজ্যুয়াল ষ্টুডিও কোড' ইনস্টল করার দরকার নেই। ইনস্টল করতে চাইলে ইন্টারনেট আর 'অ্যাডমিনিস্ট্রেটিভ প্রিভিলেজ' লাগবে।<br>
৮. নেক্সট, নেক্সট এর পর 'ফিনিশ' বাটন চাপ দিয়ে ইনস্টলেশন শেষ করে দিন। ইনস্টলেশন শেষে উইন্ডোজ স্টার্ট মেন্যুতে গিয়ে 'অ্যানাকন্ডা নেভিগেটর' দেখতে পারেন। অসাধারণ সব জিনিসপত্র। আমাদের লাগবে না এমুহুর্তে। <br>
৯. সার্চ বক্সে লিখুন Anaconda Navigator, পুরো লিখতে হবে না। চলে আসবে আমাদের নেভিগেটর। <br>

# সাইকিট-লার্ন

ওপেনসোর্স মেশিন লার্নিং এর হৃদয় হচ্ছে এই 'সাইকিট-লার্ন'। অনেকে একে 'এসকে-লার্ন' বলে থাকেন। এখন একটু এই আসল 'সাইকিট-লার্ন' মেশিন লার্নিং লাইব্রেরি নিয়ে কথা বলি। এটা একটা অসাধারণ ওপেনসোর্স প্রজেক্ট, ফ্রি - সঙ্গে সোর্স কোড উন্মুক্ত। গিটহাবে গেলে দেখা যায় এই 'সাইকিট-লার্ন'এর হৃদয়। লাইন বাই লাইন। কিভাবে কাজ করে ভেতরে। সেকারণে দেখা যায় এর ভেতরের কাজ কারবার। এর ডেভেলপমেন্টে আছে বিশাল 'অ্যাক্টিভ' ইউজার কম্যুনিটি। এর ভেতরে প্রচুর নামকরা অ্যালগরিদম আছে যার ডকুমেন্টেশন পড়ে শিখেছি অনেক কিছু। মানে এই বুড়ো বয়সে।
আমার দেখামতে, ইন্ডাস্ট্রি, একাডেমিয়া - সব জায়গায় চলে এই জিনিস। বিশাল বিশাল প্রজেক্টে চলছে এই জিনিস। হাজারো স্টার্ট-আপের লাইফ লাইন হচ্ছে এই টুলস। স্টার্ট-আপদের শুরুতে টাকা কই? সবচেয়ে বড় জিনিস হচ্ছে ইন্টারনেটে ভর্তি এর হেল্প ফাইল আর টিউটোরিয়াল। 'সাইকিট-লার্ন'এর সাথে অন্য সাইন্টিফিক পাইথন টুলগুলোর ইন্টিগ্রেশন অনেক অনেক ভালো। আর তাই একে অনেক সময় 'সাইকিট-লার্ন' এপিআই হিসেবে বলে থাকি আমরা। আমার দেখামতে পৃথিবীর কয়েকটা সেরা ইউজার জেনারেটেড ডকুমেন্টেশন প্রজেক্ট হচ্ছে এই 'সাইকিট-লার্ন'। অসম্ভব ভালো বলে এর কম্যুনিটি হেল্প ওয়ার্ল্ড ক্লাস।

# পান্ডাজ

পাইথনের একটা অসাধারণ লাইব্রেরি হচ্ছে পান্ডাজ, বিশেষ করে ডেটা ম্যানিপুলেশন আর অ্যানালাইসিসের জন্য। মনে আছে 'আর' এনভায়রনমেন্ট এর 'ডেটাফ্রেম' এর কথা। 'আর' যেহেতু স্ট্যাটিসটিক্সকে ঘিরে বানানো, সেকারণে তারা তৈরি করেছিলো ডেটাফ্রেম, কাজে গতি আনতে। এই ডেটাফ্রেমই পাল্টে দিয়েছে ডেটা ম্যানিপুলেশন আর অ্যানালাইসিসের পার্সপেক্টিভ। আচ্ছা, ডেটাফ্রেম কী? 
উত্তর দেবার আগে আপনাকে যদি বলা হয় পৃথিবীর সবচেয়ে সোজা, ইউজার ফ্রেন্ডলি ডেটা ম্যানিপুলেশন টুল কী? ঠিক বলেছেন মাইক্রোসফট এক্সেল। এই ডেটাফ্রেম হচ্ছে এক্সেলের মতো একটা টেবিল। এক্সেল যেভাবে টেবিলে ডেটা এক্সেস, সেটার দরকারি মডিফিকেশন করতে যতো সুবিধা দেয় সেটা অতো সহজে কেউ করে দিতে পারে না। সেই একই কাজ করা যায় এই ডেটাফ্রেমে। 
এছাড়া সিকুয়েল ধরণের কোয়েরি, টেবিল 'জয়েন' করানো তার জন্য মামুলি ব্যাপার। 'নামপাই' থেকে এর সুবিধা অনেক বেশি। 'নামপাই' অ্যারেতে প্রতিটা এন্ট্রি এক ধরণের হতে হয় সেখানে পান্ডাজ টেবিল প্রতিটা কলামকে আলাদা আলাদা ডেটাটাইপ (যেমন, ইন্তেজার, ডেট, ফ্লোটিং পয়েন্ট নম্বর, স্ট্রিং) রাখতে কোন ঝামেলা করে না। এটাই বিশাল পাওয়া। 

In [1]:
import pandas as pd
# create a simple dataset of people
data = {'Name': ["জসিম", "করিম", "মিতা", "অন্তরা"],
        'Location' : ["রাজশাহী", "ঢাকা", "রংপুর", "কুষ্টিয়া"],
        'Age' : [24, 13, 53, 33]
       }

frame = pd.DataFrame(data)
# ডেটাফ্রেম দেখলেই আপনার মন ভালো হয়ে যাবে, একদম এক্সেল 
display(frame)

Name  Location  Age
0    জসিম   রাজশাহী   24
1    করিম      ঢাকা   13
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

In [2]:
#কোয়েরি চালাই একটু

display(frame[frame.Age > 30])

Name  Location  Age
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

# নামপাই

পাইথন দিয়ে ডাটা সাইন্স এর কাজ করতে চাইলে ‘নামপাই’ একদম গোড়ার প্যাকেজ। মানে এটা ছাড়া চলবে না। সাইন্টিফিক কম্পুটিং এর ‘অ্যারে’র সব কাজ করে এই ‘নামপাই’ ডাটা স্ট্রাকচার। যদি হাই লেভেল ম্যাথমেটিক্যাল ফাংশনের কথা বলি, তাহলেও দরকার এই ‘নামপাই’কে। লিনিয়ার এলজেব্রা, ফোরিয়ের ট্রান্সফর্মেশন, আবার শুধুমাত্র র‌্যান্ডম নাম্বার জেনারেটর হিসেবেও এর কাজ অসাধারণ।
মেশিন লার্নিং এর ভেতরের সাইন্টিফিক কম্পুটিং করার জন্যই আমরা ব্যবহার করছি ‘নামপাই’। সত্যি কথা বলতে ‘সাইকিট-লার্ন’ দাঁড়িয়ে আছে নামপাই অ্যারে ডাটা স্ট্রাকচারের ওপর। ‘সাইকিট-লার্ন’ আসলে ডাটা নেয় ‘নামপাই’ অ্যারে থেকে। আমরা বাইরে থেকে যতো ডাটা নেই না কেন সেটাকে প্রথমে কনভার্ট করতে হবে এই নামপাই অ্যারেতে। নামপাই এর কোর ‘ফাংশনালিটি’ হচ্ছে এনডি-অ্যারে, মানে ‘এন’ সংখ্যক ডাইমেনশনাল অ্যারে নিয়ে ডাটা স্ট্রাকচারে।
একটা অ্যারে তৈরি করে দেখাই এখানে।

In [3]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [4]:
#অথবা, একটা রেঞ্জ লেখি 
y = np.arange(10)  
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#নামপাই এর অ্যারেকে স্লাইস
import numpy as np
# আমরা একটা অ্যারে তৈরি করি যার শেপ হচ্ছে (৩, ৪)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# স্লাইসিং করে আমরা একটা সাব-অ্যারে বের করে নিয়ে আসি শুধুমাত্র প্রথম দুটো সারি থেকে 
# প্রথমে চারটা কলাম, পরে দুটো - দুটো অ্যারে শেপ দিয়ে (২, ৪) এবং (২, ২) 
b = a[:2, 1:3]
c = a[:2]

print(c)
print(b)


[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]


# ডেটা সাইন্সের পাইথন

১. আমরা প্রোগ্রামিং এর কাজ কমাতে গিয়ে তার কাজগুলোকে বিভিন্ন ফাংশনে ভাগ করি। একেকটা ফাংশন মানে একটা করে স্পেসিফিক কাজ। এই ফাংশন মানে এমন একটা রুল তৈরি করা যেটা যেকোন সংখ্যক ইনপুট থেকে তার করেসপন্ডিং আউটপুট বানিয়ে দেয়। ফাংশনকে 'ডিফাইন' করে সেটাকে কল করা, যাতে একই জিনিস বার বার নতুন করে তৈরি করতে না হয়। যেমন, শুরুতে ডিফাইন করলাম my_function()কে। <br>
def my_function():<br>
  print("Hello from a function")<br>

এখন ব্যবহার করার জন্য কল করছি my_function()কে। একটা জিনিস মনে রাখতে হবে - শেষে () ব্যবহার করতে হবে। এখানে কিছুটা পজিশনাল এবং কীওয়ার্ড (kwarg=value) দুটো প্যারামিটার লাগতে পারে যা এমুহুর্তে প্রয়োজন পড়ছে না। <br>
my_function()<br>
Output = Hello from a function

পাইথন ফাংশনগুলো ফার্স্ট ক্লাস, মানে একে অ্যাসাইন করতে পারি ভ্যারিয়েবলে আবার সেটাকে ফাংশনে বের করে দিতে পারি অন্য যেকোন আর্গুমেন্টের মতো। <br>
def double(x):<br>
return x * 2

২. ডিকশনারি, লিস্ট, সেট তৈরি। তারপর সেটাকে এক্সেস এবং 'আইটারেট' করতে পারা।<br>
tel = {'rafiq': 4098, 'mim': 4139}<br>
tel['karim'] = 4127<br>
এখন tel কী দেখাবে?<br>
tel<br>
Output = {'rafiq': 4098, 'mim': 4139, 'karim': 4127} <br>


৩. ডিকশনারি লুপিং করলে কেমন হয়?  items() মেথড ব্যবহার করে?<br>
mlbooks = {'data science from scratch': 'joel grus', 'python data science hadnbook': 'jake vanderplas'}<br>
for k, v in mlbooks.items():<br>
   print(k, v)<br>
Output = data science from scratch joel grus<br>
python data science hadnbook jake vanderplas<br>

for loops অথবা if/else কন্ডিশনাল এক্সপ্রেশন এবং কন্ডিশনাল ব্লক <br>
words = ['cat', 'window', 'defenestrate']<br>
for w in words:<br>
   print(w, len(w))<br>
Output= <br>
cat 3<br>
window 6<br>
defenestrate 12<br>

৪. লিস্ট আরো সহজ। কিছু ভ্যালুকে একসাথে গ্রূপ করা। এটা মেশিন লার্নিং ডেটা ম্যানিপুলেশনে বেশ লাগে। আমাদের ডেটাসেটে এক্সেস করতে লাগবে। <br>
squares = [1, 4, 9, 16, 25]<br>
squares<br>
আউটপুট = [1, 4, 9, 16, 25]<br>
এখন যদি আলাদা করে ভ্যালুগুলোকে এক্সেস করি, ইনডেক্স করে ভ্যালু রিটার্ন করা  <br>
squares[0]<br>
আউটপুট = 1<br>
squares[-1]<br>
আউটপুট = 25<br>
স্লাইস অপারেশন নতুন লিস্ট তৈরি করবে আগের আইটেম দিয়ে। কপি করে। <br>
squares[:]<br>
আউটপুট = [1, 4, 9, 16, 25]<br>
squares[:2]<br>
আউটপুট = [1, 4]<br>

৫. স্ট্রিং ফরম্যাটিং (যেমন, '%.2f' % 3.14)<br>
<br>
৬. ভ্যারিয়েবল, অ্যাসাইনমেন্ট, বেসিক ডেটা টাইপ (int, float, bool, str), বিভিন্ন অপারেটর +, -, * এবং /<br>
width = 20<br>
height = 5 * 9<br>
width * height<br>
আউটপুট = 900<br>

নিচের এই ধারণাটা আরো পরিষ্কার হবে বিভিন্ন অপারেটর নিয়ে, মনে আছে তো লাস্ট প্রিন্টেড অপারেটর? ক্যালকুলেটরের মতো?<br>
tax = 12.5 / 100<br>
price = 100.50<br>
price * tax<br>
আউটপুট = 12.5625<br>
price + _<br>
আউটপুট = 113.0625<br>
round(_, 2)<br>
আউটপুট = 113.06<br><br>

৭. 'পাস' স্টেটমেন্ট, যদিও কিছুই করে না তবে দরকার। পাইথনে এটা একটা  null স্টেটমেন্ট তবে 'কমেন্ট' আর 'পাস' এর মধ্যে পার্থক্য হচ্ছে পাইথন ইন্টারপ্রেটার কমেন্টকে পুরোপুরি না দেখার ভান করলেও পাসকে 'প্লেসহোল্ডার' হিসেবে ব্যবহার করে। ধরা যাক, আমরা একটা লুপ অথবা ফাংশনকে এখনই ইমপ্লিমেন্ট না করে সেটাকে ইমপ্লিমেন্ট করতে চাচ্ছি ভবিষ্যতে। সমস্যা হচ্ছে সেটাকে তো আর ফাঁকা রাখা যাবে না। রাখলেই ইন্টারপ্রেটার সমস্যা করবে। সেকারণে আমরা পাস স্টেটমেন্ট ব্যবহার করবো একটা ডামি টাইপ জিনিস বানানোর জন্য যেটার কোন কাজ নেই। <br>
pass is just a placeholder for functionality to be added later<br>
sequence = {'p', 'a', 's', 's'}<br>
for val in sequence:<br>
    pass<br>
এখন কাজ করবো, সেটা ফাংশন অথবা ক্লাস হতে পারে <br>
def function(args):<br>
    pass<br>
    অথবা <br>
class example:<br>
    pass <br>
আমরা যখন পাইথন ইন্টারপ্রেটার থেকে বের হয়ে যাই, তখন সব ডেফিনেশন (আর তার ভেতরের সব ফাংশন এবং ভ্যারিয়েবল) হারিয়ে যায়। আর সেকারণে আমরা যখন বড় কিছু তৈরি করি, তখন বড় বড় ফাংশনকে মডিউলে ভাগ করে স্টোর করে রাখি আমাদের সুবিধার্থে। এখন এই মডিউলে এক্সেস করার উপায় কী?<br><br>

৮. মেশিন লার্নিং থার্ড পার্টি লাইব্রেরিতে ব্যবহার করা বিভিন্ন মডিউল<br>

৮.১. পাইথনের জন্য ব্যবহার করা মেশিন লার্নিং এর সব ফিচার কিন্তু শুরুতেই লোড হয় না ডিফল্ট হিসেবে। আর সেটা আমাদের এই ল্যাঙ্গুয়েজের জন্য হোক - অথবা ডাউনলোড করা থার্ড পার্টি হোক। সেই মডিউলের ওই ফিচারটা ব্যবহার করতে হলে সেই মডিউলটাকে ইমপোর্ট করে নিতে হবে আগে। আগেই বলেছি, এখানে pandas হচ্ছে একটা পাওয়ারফুল ডাটা এনালাইসিস পাইথন লাইব্রেরি যেটা তৈরি করা হয়েছে numpy এর ওপর। numpy হচ্ছে আরেকটা পাইথন লাইব্রেরি যা আমাদেরকে ডাটার 'অ্যারে' ব্যবহার করতে সাহায্য করে।<br>
import pandas<br>
একটা মডিউলের সবকিছু ইমপোর্ট করতে চাইলে <br>
from sklearn.datasets import *<br><br>

৮.২. আবার যেই মডিউল আমরা ইমপোর্ট করি না কেন, সেটাকে ছোট করে নেয়া যায় 'এলিয়াস' মানে ছোট নাম দিয়ে। এখানে আমরা pandas ডাটাফ্রেমকে ইমপোর্ট করছি, সেটাকে নতুন করে অ্যাসাইন করছি pd নেমস্পেস দিয়ে। সংক্ষিপ্ত করতে। সংক্ষিপ্ত না করেও কাজ করা যায়।<br>
import pandas as pd<br>
import matplotlib.pyplot as plt<br><br>

৮.৩. এখানে আপনি pandas কে ইমপোর্ট করে সেখানে তার ছোট্ট নাম দিয়ে কাজ করতে পারবেন পুরো ডকুমেন্ট ধরে। মডিউলের ইমপোর্ট এর পর আপনি তার ফাংশনগুলোকে এক্সেস করতে চাইলে মডিউলের পর (.) ডট দিয়ে মেথডগুলো ব্যবহার করবো। এরপর আমরা pandas লাইব্রেরি থেকে read_csv মেথড ব্যবহার করবো আমাদের কম্পিউটারে রাখা একটা csv ফাইল পড়তে। সেটাকে তারপর আমরা পাঠাবো ডাটাফ্রেমে। এখানে read_csv মেথডটা পুরো টেবিলটাকে পাঠাবে প্রথম সারিটাকে ডাটাফ্রেমের হেডার হিসেবে। প্রথম সারি মানে সেখানে ফিল্ডের নাম থাকে।<br>
pd.read_csv<br><br>

৮.৪. আমরা যদি কোন মডিউলের কি কি নাম ডিফাইন করা আছে সেটা দেখতে চাইলে dir() ফাংশন ব্যবহার করতে পারি। উদাহরনটা বোঝা যাবে আরেকটু ভেতরে গেলে। <br>
from sklearn import datasets<br>
iris = datasets.load_iris()<br>
dir(iris)<br>
আউটপুট = ['DESCR', 'data', 'feature_names', 'target', 'target_names']<br>


# জুপিটার নোটবুক

ডাটা সাইন্স এর জন্য যত টুল আমরা ব্যবহার করব তারমধ্যে প্রোডাক্টিভিটির দিক থেকে ‘জুপিটার নোটবুক’ সেরা। জিনিসটা একেবারেই গডসেন্ড। ডাটা সাইন্স এর কাজকে পানির মতো করে নিয়ে এসেছে আমাদের এই জুপিটার নোটবুক। পাইথন বা “আর” প্রোগ্রামিং এনভায়রনমেন্ট এর কনসোলে কাজ করার ভীতিকর অবস্থাকে একদম নাই করে দিয়েছে এই নোট বুক। এক ফাইলে নিয়ে এসেছে সবকিছু। 'ইন্টারেক্টিভ' বলতে যা বোঝায় আরকি। নোটবুকের মতো সব রেখে দেয় নিজের ভেতর। <br>
তো, এই নোট বুক বা ‘নোটবুক ডকুমেন্ট’ কি? <br>
১. এই এক নোটবুকে আপনার কোড, ডাটা ভিজুয়ালাইজেশন, হাজারো ন্যারেটিভ টেক্সট মানে কোড এর পাশাপাশি তার বিস্তারিত গল্প, দরকারি ম্যাথমেটিক্যাল ইকুয়েশন, লিংক আর সব ধরনের রিচ মিডিয়া রাখতে পারবেন কোন কষ্ট ছাড়াই। এক ফাইলে। <br>
২. সবকিছু এক ফাইলে ‘রাখতে পারার’ কারণেই এটা অনলাইনে শেয়ার করার সহজ। সব কনটেন্টকে সে ‘এমবেড’ করে নিয়ে এসেছে একটা ফাইলে। তুলে দেন গিটহাবে। চলে আসবে লেখা, গ্রাফিক্স, ইক্যুয়েশন, ডাটা ভিজুয়্যালাইজেশন, মজার জিনিস না? <br>
৩. Jupyter নামটা এসেছে তিনটা প্রোগ্রামিং এনভায়রনমেন্টের আদ্যক্ষর থেকে। জুলিয়া, পাইথন এবং "আর"। তবে, এখন এই নোটবুক সাপোর্ট করে প্রায় সব এনভায়রনমেন্ট।  <br>
৪. আগেই যেহেতু আমরা 'অ্যানাকন্ডা' ইনস্টল করে এসেছি, তাই 'জুপিটার নোটবুক’ ইনস্টল হয়ে আছে আগে থেকে। এখন শুধু চালু করতে হবে। 
৫. স্টার্ট মেন্যুর 'সার্চ বাটনে গিয়ে লিখুন "Jupyter Notebook"। আমার ধারণা পুরোটা লিখতে হবে না। যেমন আমি শুধুমাত্র "J" লিখলেই পুরোটা চলে আসে। হয়তোবা আমার পিসিতে ওই আদ্যক্ষর দিয়ে কোন ডেস্কটপ অ্যাপ নেই। আপনাদেরও থাকার কথা নয়।  <br>
৬. প্রথমবারের মতো জুপিটার নোটবুক চালু হতে একটু সময় নিতে পারে। এটা আসলে একটা ক্লায়েন্ট সার্ভার অ্যাপ। পেছনে একটা ওয়েব সার্ভার (দুই প্রসেসের কার্নাল আর্কিটেকচার) চলছে নোটবুক সার্ভার হিসেবে। আপনি চাইলে রিমোট থেকেও কাজ করতে পারেন সামান্য কনফিগারেশন পাল্টে।  <br>
৭. আমাদের নোটবুক চালু হবে ওয়েব ব্রাউজারে। http://localhost:8888 অ্যাড্রেস নিয়ে। সবচেয়ে ডানে গিয়ে "নিউ" বাটনে চাপ দিলেই চলে আসবে "পাইথন", আমরা একটা পাইথনে নোটবুক খুলবো।  <br>
৮. নোটবুক চালু করলে একটা ইন্টারফেস চলে আসবে। "ইন" সেলের মধ্যে লিখবো আমাদের কোড, মার্কআপ ল্যাঙ্গুয়েজ পছন্দমতো।  <br>
৯. জুপিটার নোটবুক এর সব মেন্যুগুলোর নাম দেখলে মাইক্রোসফট ওয়ার্ড এর কথা মনে পড়বে। এখানে দুটো মেন্যু হয়তোবা নতুন। একটা হচ্ছে “সেল” আরেকটা “কার্নাল”। পুরো জুপিটার নোটবুকে আমরা কাজ করব “সেল” দিয়ে। একেকটা “সেল” হচ্ছে আমাদের কাজের মানে লেখার জায়গা। ওই জায়গাগুলোতে আমরা কোড অথবা বোঝানোর জন্য মার্কআপ ল্যাংগুয়েজ ব্যবহার করতে পারি। ছবি দেখুন, In [ ] দিয়ে শুরু হয়েছে একেকটা সেল। সবুজ রঙের বার দেয়া। ওখানেই লিখতে হবে আমাদের। এই “সেল” এ যাই লিখব সেটাই নোটবুক কার্নেলের মাধ্যমে একজিকিউট হয়ে আসবে। <br>
তার মানে, “সেল” হচ্ছে নোটবুক এর ভেতরে একটা লেখার জায়গা, যা আমাদের কমান্ডগুলো পাঠায় নোটবুকের “কার্নাল” এ। <br>
“কার্নাল” হচ্ছে নোটবুকের “কম্পিউটেশনাল ইঞ্জিন” যা আমাদের নোটবুক ডকুমেন্টের কোডকে চালায়। ভেতর থেকে। নোটবুকের হৃদয় হচ্ছে এই “কার্নাল”। <br>
১০. তবে আমাদের কাজের জন্য “সেল” এর কাজ জানা উচিত। “কোড” ড্রপডাউন মেনুতে চারটা অপশন আছে। এই মুহূর্তে আমরা প্রথম দুটি ব্যবহার করব। প্রথমটা “কোড” সেল, পরেরটা “মার্কডাউন” সেল। <br>
১১. “কোড” সেল সিলেক্ট করে আমরা যখন কোন কিছু লিখে “রান” কমান্ড চাপবো, তখন ওটা সরাসরি চলে যাবে নোটবুকের কার্নাল এ। কিবোর্ডে “কন্ট্রোল + এন্টার” একসাথে চাপলেও রান হয়ে যাবে। আউটপুট ফিরে আসবে পরের লাইনে। পরের ছবিটি দেখুন। <br>
১২. আমরা যখন “মার্কডাউন” সেল সিলেক্ট করে কোন কিছু লিখব, তখন সেটা “রান” করলে ফিরে আসবে মার্কডাউন ল্যাঙ্গুয়েজে। এটা ব্যবহার করব কমেন্ট আকারে বিভিন্ন জিনিস লেখার জন্য।  <br>